### ISSUE TITLE
RuntimeError: The size of the 2D attn_mask is not correct

### ISSUE THREAD

**Issue by wssxjtu** [TuanTNG/SimOn#6]
excuse me，when I run your program, I get the following error and want to know how to fix it. Thank you

Not using distributed mode
lr:0.0001
batch_size:256
weight_decay:0.0001
epochs:17
lr_drop:3
gamma:0.5
clip_max_norm:1.0
model_name:SimOn
ignore_index:21
feature:thumosV3
num_decoder_layers:4
dim_feature:3072
numclass:22
dropout:0.1
feat_forward_dim:256
d_model:256
nhead:8
pickle_root:/data1/wss/thumos14_anet
train_num_videoframes:128
train_stride:128
test_num_videoframes:2048
test_stride:2048
device:cuda
output_dir:models/odas_thumos_anet_decoder_layer4_kv7
removelog:False
seed:20
resume:
start_epoch:1
eval:False
num_workers:8
history_desision:6
history_feature:6
max_lengh_clip:5000
distributed:False
dataparallel:False
world_size:1
dist_url:tcp://127.0.0.1:12342
number of params: 3567894
loading val dataset.......................
load thumos_all_feature_val_tsn_v2.pickle !
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:05<00:00, 37.66it/s]
loading test dataset.......................
load thumos_all_feature_test_tsn_v2.pickle !
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 213/213 [00:16<00:00, 12.62it/s]
Start training
max length sequence:  8
Traceback (most recent call last):
  File "main.py", line 159, in <module>
    main(args)
  File "main.py", line 115, in main
    optimizer, device, epoch, args.clip_max_norm, args=args)
  File "/data1/wss/Code/SimOn-ODAS/train.py", line 136, in train_one_epoch
    cls_scores = model(camera_inputs, is_starts, pre_probs)
  File "/home/wss/anaconda3/envs/SimOn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data1/wss/Code/SimOn-ODAS/simon/simon.py", line 117, in forward
    outs = self.transformer(queries, memory, target_mask)
  File "/home/wss/anaconda3/envs/SimOn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wss/anaconda3/envs/SimOn/lib/python3.7/site-packages/torch/nn/modules/transformer.py", line 234, in forward
    memory_key_padding_mask=memory_key_padding_mask)
  File "/home/wss/anaconda3/envs/SimOn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wss/anaconda3/envs/SimOn/lib/python3.7/site-packages/torch/nn/modules/transformer.py", line 364, in forward
    key_padding_mask=tgt_key_padding_mask)[0]
  File "/home/wss/anaconda3/envs/SimOn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wss/anaconda3/envs/SimOn/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 987, in forward
    attn_mask=attn_mask)
  File "/home/wss/anaconda3/envs/SimOn/lib/python3.7/site-packages/torch/nn/functional.py", line 4729, in **multi_head_attention_forward
    raise RuntimeError("The size of the 2D attn_mask is not correct.")
RuntimeError: The size of the 2D attn_mask is not correct.**

**Comment by TuanTNG** [comment]
Hi,

Thank you for your interest,
I have not encountered this error yet.
Did you modify any thing?
